### ISSUE TITLE
Unable to resolve non-existing file

### ISSUE THREAD

**Issue by ennio-tomas** [yanai101/css-var-hint#2]
Not working, gives me error: Unable to open 'config.scss': Unable to read file 'c:\D:\Demo.com\css\config.scss' (Error: Unable to resolve non-existing file 'c:\D:\Demo.com\css\config.scss'). Looks like extension adds additional "c:" drive letter to the path. How can I fix it? Thanks

![Code_cxaIAGMIa3](https://user-images.githubusercontent.com/82775948/115156564-7513d900-a08d-11eb-86e9-67e3b6d27218.png)

**Comment by yedri101** [comment]
Hi - can you give more info about the system ? i see that -  the path is weird  - "c:\D:\..." -  this is the right path?

**Comment by ennio-tomas** [comment]
WIN 10, VS Code in C drive, project files in D:\Demo.com folder.

Extension is trying to locate D:\Demo.com folder in C drive.

**Comment by yedri101** [comment]
thanks - i will check it!

**Comment by ennio-tomas** [comment]
VS Code 1.55.2 portable version.

**Comment by yanai101** [comment]
@ennio-tomas  thanks for the issue - this is fixed in version 0.2.14

**Comment by yanai101** [comment]
this is fixed in version 0.2.14
