### ISSUE TITLE
Search in VS Code Marketplace

### ISSUE THREAD

**Issue by onetrev** [yanai101/css-var-hint#4]
Sorry this may not be the best place to note this, but I wanted to let you know that this extension shows up way down the list of search results in the VS Code Marketplace when searching for "CSS variables". 

I'm not sure if there is anything you can do to improve the keywords / search results? It should show up right at the top because it's a pretty new extension, well rated, still maintained, and works perfectly! :)

**Comment by yanai101** [comment]
Thanks , I will check it ! ☺️

**Comment by onetrev** [comment]
I noticed unfortunately your extension still doesn't show up very easily in the Marketplace. :(  Which is too bad because it works so much better (since it works with SCSS files!) than the much more popular [CSS Custom Properties](https://marketplace.visualstudio.com/items?itemName=Tock.vscode-css-custom-properties) extension.

I wondered if would also help if you had some keywords for "custom properties" instead of vars / variables? It seems that more and more people are starting to use the offical name of custom properties instead of variables now.

**Comment by yanai101** [comment]
Hi.
Sorry about the delay - but thanks for the suggestion - added 👍
